# Simulated daily request to your render project so that the service doesn't go down
name: Keep-Alive Render Ping

on:
  schedule:
    - cron: '*/14 * * * *'  # Tatakbo na ito tuwing ika-14 na minuto (24/7)
  workflow_dispatch:      # Para pwede mong i-test manually sa GitHub Actions tab

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://hackaton-website.onrender.com
